#!/bin/sh

ENABLED=yes
PROCS=php81-fpm
ARGS="--nodaemonize --fpm-config /opt/etc/php81-fpm.conf -R"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
